import './globals.css'
import 'swiper/css';
import Header from "@/components/common/header/Header";
import Footer from "@/components/common/footer/Footer";

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>
                <Header />

                <>
                    {children}
                </>

                <Footer />
            </body>
        </html>
    )
}
